import type { Scan } from "../types";

export const accountancyScan: Scan = {
  slug: "administratiekantoor",
  title: "Hoe volwassen is jouw administratieve proces?",
  subtitle: "Ontdek in zes minuten waar in je kantoor de meeste tijd weglekt.",
  audience: "Voor accountants- en administratiekantoren",
  intro: "Vierentwintig vragen over aanlevering, verwerking, periodeafsluiting en sturing. Je ziet direct je score per onderdeel en krijgt een verbeterrapport in je mailbox.",
  subject: "kantoor",
  categories: [
    {
      code: "A",
      name: "Aanlevering & klantregie",
      weight: 0.2,
      lowScoreText:
        "De aanlevering door je klanten bepaalt je hele planning. Zolang stukken binnenkomen wanneer het de klant uitkomt, kun je je capaciteit niet plannen en verschuift het werk naar de piekmomenten rond de aangifte. De eerste ingreep is niet strenger zijn, maar makkelijker maken: één vaste digitale route, één moment per maand en een geautomatiseerde herinnering.",
    },
    {
      code: "B",
      name: "Applicatielandschap & koppelingen",
      weight: 0.15,
      lowScoreText:
        "Elke handmatige overstap tussen twee applicaties is een plek waar tijd en kwaliteit weglekken. Begin met een plaat van je applicatielandschap: welke applicatie ondersteunt welke stap, en waar worden dezelfde gegevens twee keer ingevoerd. In de praktijk zitten daar bijna altijd twee of drie koppelingen die zichzelf binnen een jaar terugverdienen.",
    },
    {
      code: "C",
      name: "Verwerking & automatisering",
      weight: 0.2,
      lowScoreText:
        "Verwerking is de plek waar automatisering het snelst rendeert, maar alleen als je de uitval meet. Zonder cijfer over het aandeel handmatige correcties blijft het gissen welke klant of welke leverancier het probleem veroorzaakt. Meet vier weken lang, en de top vijf van oorzaken ligt er.",
    },
    {
      code: "D",
      name: "Datakwaliteit & vraagposten",
      weight: 0.15,
      lowScoreText:
        "Vraagposten en tussenrekeningen die doorschuiven, zijn uitgesteld werk met rente. Wat in maart een vraag van één minuut aan de klant was, kost in december een halve dag reconstructie. Actieve monitoring op de vraagpostenrekening, met directe uitvraag bij de klant, is een van de ingrepen met de kortste terugverdientijd.",
    },
    {
      code: "E",
      name: "Periodeafsluiting & aangiften",
      weight: 0.15,
      lowScoreText:
        "Als perioden na rapportage open blijven staan, is geen enkel cijfer definitief en kan elke rapportage achteraf veranderen. Een vaste checklist met rolverdeling en een reviewstap, gevolgd door het daadwerkelijk sluiten van de periode, maakt van rapporteren een eindpunt in plaats van een tussenstand.",
    },
    {
      code: "F",
      name: "Sturing, meting & vastlegging",
      weight: 0.15,
      lowScoreText:
        "Zonder meetpunt per processtap stuur je op uren en op klachten. Dat is achteraf sturen. Koppel aan elke stap uit je proces één cijfer — doorlooptijd, uitval, actualiteit — en je ziet afwijkingen op het moment dat je er nog iets aan kunt doen.",
    },
  ],
  questions: [
    {
      id: 1,
      category: "A",
      text: "Hoe komen de administratieve stukken van je klanten binnen?",
      options: [
        { points: 0, label: "Wisselend per klant: post, mail, appjes, soms een doos papier" },
        { points: 1, label: "Overwegend per e-mail naar een algemeen adres" },
        { points: 2, label: "Vast e-mailadres per administratie, dat rechtstreeks in de scan- en herkensoftware landt" },
        { points: 3, label: "Via een klantportaal of scan-app, met een klein deel nog per mail" },
        { points: 4, label: "Eén vaste digitale aanleverroute voor vrijwel alle klanten, vastgelegd in de klantafspraken" },
      ],
    },
    {
      id: 2,
      category: "A",
      text: "Zijn er per klant harde afspraken over wat er wanneer wordt aangeleverd?",
      options: [
        { points: 0, label: "Nee, klanten leveren aan wanneer het hen uitkomt" },
        { points: 1, label: "Mondelinge afspraken, niet vastgelegd" },
        { points: 2, label: "Vastgelegd in de opdrachtbevestiging, maar we sturen er niet actief op" },
        { points: 3, label: "Vastgelegd en we rappelleren handmatig" },
        { points: 4, label: "Vastgelegd, geautomatiseerd gerappelleerd en we meten of klanten zich eraan houden" },
      ],
    },
    {
      id: 3,
      category: "A",
      text: "Hoe verloopt het opvragen van ontbrekende stukken?",
      options: [
        { points: 0, label: "Ad hoc per mail of telefoon; er is geen overzicht van wat openstaat" },
        { points: 1, label: "Een medewerker houdt een eigen lijstje bij" },
        { points: 2, label: "Er is een standaard checklist per klanttype" },
        { points: 3, label: "Vanuit het systeem (PBC-lijst of vraagpostenapp) met notificatie aan de klant" },
        { points: 4, label: "Geautomatiseerd, met statusoverzicht per klant en meting van de doorlooptijd" },
      ],
    },
    {
      id: 4,
      category: "A",
      text: "Weet je hoeveel tijd er zit tussen 'stuk opgevraagd' en 'stuk ontvangen'?",
      options: [
        { points: 0, label: "Nee, daar hebben we geen zicht op" },
        { points: 1, label: "Gevoelsmatig; het verschilt sterk per klant" },
        { points: 2, label: "Achteraf te reconstrueren uit het mailverkeer" },
        { points: 3, label: "We meten dit voor onze grootste klanten" },
        { points: 4, label: "Doorlooptijd is een vaste KPI, zichtbaar per klant en per team" },
      ],
    },
    {
      id: 5,
      category: "B",
      text: "Is vastgelegd welke applicatie welke processtap ondersteunt en hoe die applicaties samenhangen?",
      options: [
        { points: 0, label: "Nee, dat zit in de hoofden van een paar mensen" },
        { points: 1, label: "Er is een lijst met applicaties, zonder samenhang" },
        { points: 2, label: "Er is een globaal schema, maar het is verouderd" },
        { points: 3, label: "Er is een actueel schema van applicaties en koppelingen" },
        { points: 4, label: "Actueel schema inclusief datastromen, eigenaarschap per applicatie en een jaarlijkse review" },
      ],
    },
    {
      id: 6,
      category: "B",
      text: "Hoe vaak worden dezelfde gegevens in meer dan één systeem ingevoerd (klantgegevens, uren, relaties)?",
      options: [
        { points: 0, label: "Structureel, bij vrijwel elke nieuwe klant en elke mutatie" },
        { points: 1, label: "Regelmatig, het is een bekende ergernis" },
        { points: 2, label: "Bij een paar systemen die niet gekoppeld zijn" },
        { points: 3, label: "Zelden; de belangrijkste koppelingen liggen er" },
        { points: 4, label: "Nooit; klantdata wordt op één plek onderhouden en gesynchroniseerd" },
      ],
    },
    {
      id: 7,
      category: "B",
      text: "Hoe verloopt de keten van CRM en urenregistratie naar facturatie en dossier?",
      options: [
        { points: 0, label: "Facturen worden handmatig opgesteld buiten de urenregistratie om" },
        { points: 1, label: "Uren worden handmatig overgenomen in de facturatie" },
        { points: 2, label: "Uren en facturatie zijn gekoppeld, het dossier staat er los van" },
        { points: 3, label: "CRM, uren, facturatie en klantportaal zijn gekoppeld" },
        { points: 4, label: "Volledig gekoppeld: bij een nieuwe klant worden omgeving, dossier en dienstenpakket automatisch aangemaakt" },
      ],
    },
    {
      id: 8,
      category: "B",
      text: "Hoe worden documenten en dossierstukken vastgelegd?",
      options: [
        { points: 0, label: "Op lokale schijven en in de mailboxen van medewerkers" },
        { points: 1, label: "Op een netwerkschijf, met per medewerker een eigen mappenstructuur" },
        { points: 2, label: "Centrale opslag met een vaste mappenstructuur" },
        { points: 3, label: "Centrale opslag, gekoppeld aan het klantdossier in de vakapplicatie" },
        { points: 4, label: "Eén bron: dossier, portaal en opslag zijn gekoppeld, met versiebeheer en rechtenbeheer" },
      ],
    },
    {
      id: 9,
      category: "C",
      text: "Welk deel van de inkoopfacturen wordt herkend en geboekt zonder handmatige correctie?",
      options: [
        { points: 0, label: "Minder dan 25%" },
        { points: 1, label: "Tussen 25% en 50%" },
        { points: 2, label: "Tussen 50% en 70%" },
        { points: 3, label: "Tussen 70% en 90%" },
        { points: 4, label: "Meer dan 90%" },
      ],
    },
    {
      id: 10,
      category: "C",
      text: "Hoe worden bankafschriften verwerkt?",
      options: [
        { points: 0, label: "Handmatig ingelezen bestanden; afletteren gebeurt op ervaring" },
        { points: 1, label: "Handmatig ingelezen, met een aantal standaard boekingsregels" },
        { points: 2, label: "Automatische bankkoppeling bij een deel van de klanten" },
        { points: 3, label: "Automatische koppeling bij vrijwel alle klanten, afletteren grotendeels automatisch" },
        { points: 4, label: "Automatische koppeling met herkenningsregels; alleen uitzonderingen worden aangeraakt" },
      ],
    },
    {
      id: 11,
      category: "C",
      text: "Hoe komen betaal- en incassobatches tot stand?",
      options: [
        { points: 0, label: "De klant betaalt zelf; wij hebben daar geen zicht op" },
        { points: 1, label: "Handmatig samengestelde betaallijst, per mail gedeeld" },
        { points: 2, label: "Betaaladvieslijst uit de boekhouding, handmatig gedeeld en handmatig teruggekoppeld" },
        { points: 3, label: "Batch uit de boekhouding, via het portaal ter accordering, SEPA-bestand handmatig ingelezen bij de bank" },
        { points: 4, label: "Batch uit de boekhouding, geaccordeerd via het portaal en automatisch doorgezet naar de bank" },
      ],
    },
    {
      id: 12,
      category: "C",
      text: "Meet je de uitval: het aantal boekingen dat handmatig moet worden gecorrigeerd?",
      options: [
        { points: 0, label: "Nee" },
        { points: 1, label: "We merken het pas als het misgaat" },
        { points: 2, label: "Incidenteel, bij een klacht of een piek" },
        { points: 3, label: "Periodiek, per klant" },
        { points: 4, label: "Structureel per klant en per medewerker, met verbeteracties aan de bron" },
      ],
    },
    {
      id: 13,
      category: "D",
      text: "Wat is de stand van de tussen-, kruis- en vraagpostenrekeningen aan het eind van een periode?",
      options: [
        { points: 0, label: "Daar kijken we pas bij de jaarafsluiting naar" },
        { points: 1, label: "Er staat structureel een saldo dat doorschuift" },
        { points: 2, label: "We ruimen het per kwartaal op" },
        { points: 3, label: "Bij elke periodeafsluiting op nul, op enkele uitzonderingen na" },
        { points: 4, label: "Actief gemonitord; de klant wordt automatisch bevraagd zodra er saldo ontstaat" },
      ],
    },
    {
      id: 14,
      category: "D",
      text: "Hoe worden vraagposten bij de klant uitgevraagd?",
      options: [
        { points: 0, label: "Verzameld en één keer per jaar in één keer voorgelegd" },
        { points: 1, label: "Ad hoc per mail door de samensteller" },
        { points: 2, label: "Periodiek overzicht per mail" },
        { points: 3, label: "Via een vaste tool of app, met notificatie en statusopvolging" },
        { points: 4, label: "Geautomatiseerde monitoring op grootboekniveau, met directe uitvraag en meting van de reactietijd" },
      ],
    },
    {
      id: 15,
      category: "D",
      text: "Heb je zicht op de ouderdom van debiteuren en crediteuren bij je klanten?",
      options: [
        { points: 0, label: "Alleen als de klant er zelf om vraagt" },
        { points: 1, label: "Pas bij de jaarrekening" },
        { points: 2, label: "Per kwartaal, in een rapportage" },
        { points: 3, label: "Maandelijks, als vast onderdeel van de terugkoppeling" },
        { points: 4, label: "Continu zichtbaar in een dashboard, met signalering en vervolgacties" },
      ],
    },
    {
      id: 16,
      category: "D",
      text: "Hoe betrouwbaar is de administratie op het moment dat je een periode rapporteert?",
      options: [
        { points: 0, label: "Er volgen vrijwel altijd nog correcties achteraf" },
        { points: 1, label: "Regelmatig correcties op de gerapporteerde cijfers" },
        { points: 2, label: "Soms correcties, op onderdelen" },
        { points: 3, label: "Zelden; de checklist vangt het meeste af" },
        { points: 4, label: "De periode wordt afgesloten en blijft dicht; correcties zijn een uitzondering" },
      ],
    },
    {
      id: 17,
      category: "E",
      text: "Werk je met een vaste checklist voor de periodeafsluiting?",
      options: [
        { points: 0, label: "Nee, iedere medewerker doet het op eigen wijze" },
        { points: 1, label: "Er is een lijst, maar die wordt weinig gebruikt" },
        { points: 2, label: "Vaste checklist op papier of in Excel" },
        { points: 3, label: "Checklist in de vakapplicatie, verplicht af te vinken" },
        { points: 4, label: "Checklist in het systeem, met rolverdeling, reviewstap en voortgangsbewaking" },
      ],
    },
    {
      id: 18,
      category: "E",
      text: "Wordt de financiële periode daadwerkelijk afgesloten na rapportage of aangifte?",
      options: [
        { points: 0, label: "Nee, perioden blijven open staan" },
        { points: 1, label: "Alleen bij de jaarafsluiting" },
        { points: 2, label: "Meestal wel, maar niet consequent" },
        { points: 3, label: "Ja, standaard na de OB-aangifte" },
        { points: 4, label: "Ja, automatisch, met periodieke controle op openstaande perioden" },
      ],
    },
    {
      id: 19,
      category: "E",
      text: "Hoe verloopt de review op aangiften en samenstelwerk?",
      options: [
        { points: 0, label: "Er is geen formele reviewstap" },
        { points: 1, label: "Alleen bij nieuwe of complexe klanten" },
        { points: 2, label: "Vaste review, maar bevindingen worden niet vastgelegd" },
        { points: 3, label: "Vaste review, met vastlegging van de bevindingen in het dossier" },
        { points: 4, label: "Vaste review, bevindingen vastgelegd én geanalyseerd om terugkerende fouten aan de bron op te lossen" },
      ],
    },
    {
      id: 20,
      category: "E",
      text: "Hoe verlopen accordering en verzending van aangiften en jaarstukken?",
      options: [
        { points: 0, label: "Per mail, met losse pdf's en handtekeningen" },
        { points: 1, label: "Per mail, met handmatige opvolging en verzending" },
        { points: 2, label: "Via een portaal, opvolging handmatig" },
        { points: 3, label: "Via een portaal, met automatische notificatie en herinnering aan de klant" },
        { points: 4, label: "Portaal met notificaties, statusbewaking en automatische terugkoppeling in het dossier na acceptatie" },
      ],
    },
    {
      id: 21,
      category: "F",
      text: "Zijn de administratieve processen van je kantoor beschreven?",
      options: [
        { points: 0, label: "Nee" },
        { points: 1, label: "Deels, en die beschrijving is verouderd" },
        { points: 2, label: "Beschreven voor de belangrijkste processen" },
        { points: 3, label: "Beschreven per processtap, inclusief de verantwoordelijke" },
        { points: 4, label: "Beschreven per processtap, met verantwoordelijke én de rapportage of KPI per stap, jaarlijks geactualiseerd" },
      ],
    },
    {
      id: 22,
      category: "F",
      text: "Op welke stuurinformatie stuur je je administratieteam aan?",
      options: [
        { points: 0, label: "Op onderbuikgevoel en op klachten van klanten" },
        { points: 1, label: "Op declarabiliteit en gefactureerde uren" },
        { points: 2, label: "Op uren plus onderhanden werk" },
        { points: 3, label: "Op uren, onderhanden werk en doorlooptijd per klant" },
        { points: 4, label: "Op een set KPI's per processtap: doorlooptijd, uitval, actualiteit en aanleverdiscipline" },
      ],
    },
    {
      id: 23,
      category: "F",
      text: "Weet je per klant of de opdracht winstgevend is?",
      options: [
        { points: 0, label: "Nee" },
        { points: 1, label: "Pas achteraf, en alleen op kantoortotaal" },
        { points: 2, label: "Per klantgroep of dienst" },
        { points: 3, label: "Per klant, achteraf per jaar" },
        { points: 4, label: "Per klant én per dienst, gedurende het jaar zichtbaar" },
      ],
    },
    {
      id: 24,
      category: "F",
      text: "Wat gebeurt er als iemand een verbeterpunt in het proces signaleert?",
      options: [
        { points: 0, label: "Het blijft meestal bij een opmerking" },
        { points: 1, label: "Het wordt besproken; opvolging is toevallig" },
        { points: 2, label: "Het komt op een lijst en af en toe pakken we iets op" },
        { points: 3, label: "Vaste verbetercyclus, met eigenaar en deadline" },
        { points: 4, label: "Vaste cyclus, gemeten effect, en de verbetering wordt in de procesbeschrijving verwerkt" },
      ],
    },
  ],
  profileQuestions: [
    {
      id: "P1",
      text: "Wat past het best bij jouw organisatie?",
      type: "single",
      options: [
        "Accountantskantoor",
        "Administratiekantoor",
        "Belastingadvieskantoor",
        "Zelfstandig boekhouder",
        "Financiële afdeling van een bedrijf",
        "Anders",
      ],
    },
    {
      id: "P2",
      text: "Hoeveel medewerkers werken er in de administratieve praktijk?",
      type: "single",
      options: [
        "1 – 4",
        "5 – 10",
        "11 – 25",
        "26 – 50",
        "Meer dan 50",
      ],
    },
    {
      id: "P3",
      text: "Welk boekhoudpakket gebruik je overwegend?",
      type: "single",
      options: [
        "Exact Online",
        "Twinfield",
        "Visma.net / AccountView",
        "Yuki",
        "SnelStart",
        "Anders / meerdere",
      ],
    },
    {
      id: "P4",
      text: "Hoeveel administraties verwerk je per maand?",
      type: "single",
      options: [
        "Minder dan 25",
        "25 – 75",
        "75 – 200",
        "Meer dan 200",
      ],
    },
    {
      id: "P5",
      text: "Waar zit op dit moment je grootste frustratie in het proces?",
      type: "text",
    },
    {
      id: "P6",
      text: "Wat wil je over twaalf maanden bereikt hebben?",
      type: "multi",
      options: [
        "Minder handwerk in de verwerking",
        "Hogere marge per opdracht",
        "Meer volume aankunnen zonder extra fte",
        "Betere datakwaliteit en minder correcties",
        "Meer ruimte voor advieswerk",
        "Kantoor minder afhankelijk van sleutelpersonen",
      ],
    },
  ],
  tiers: [
    {
      min: 0,
      max: 0.39,
      level: "Niveau 1 — Reactief",
      headline: "Het proces stuurt jou, in plaats van andersom",
      body:
        "Je administratie draait, maar vooral op inzet van mensen en op het geheugen van een paar sleutelfiguren. Werk komt binnen zoals het binnenkomt, en het kantoor past zich daaraan aan.",
      recognise: [
        "Aanlevering verschilt per klant en is niet afdwingbaar",
        "Correcties achteraf zijn eerder regel dan uitzondering",
        "Pieken rond aangiftemomenten worden opgevangen met overwerk",
      ],
      steps: [
        "Leg één proces vast — de periodeafsluiting — met per stap een verantwoordelijke",
        "Maak één aanleverroute verplicht voor alle nieuwe klanten",
        "Meet vier weken lang hoe lang klanten erover doen om stukken aan te leveren",
      ],
    },
    {
      min: 0.4,
      max: 0.59,
      level: "Niveau 2 — Beheerst handwerk",
      headline: "Het loopt, maar het loopt op mensenkracht",
      body:
        "De basis staat: er zijn afspraken, er is software en het werk komt af. De winst zit nu niet meer in harder werken, maar in het wegnemen van de handmatige schakels tussen je systemen.",
      recognise: [
        "Dezelfde gegevens worden op meerdere plekken ingevoerd",
        "Vraagposten en tussenrekeningen schuiven door naar de volgende periode",
        "Je stuurt op uren, nog niet op doorlooptijd en uitval",
      ],
      steps: [
        "Breng het applicatielandschap en de dubbele invoer in kaart",
        "Automatiseer het uitvragen van vraagposten en ontbrekende stukken",
        "Zet twee KPI's op: uitvalpercentage en doorlooptijd per administratie",
      ],
    },
    {
      min: 0.6,
      max: 0.79,
      level: "Niveau 3 — Gestroomlijnd",
      headline: "Het proces staat; de sturing kan scherper",
      body:
        "Je kantoor heeft de belangrijkste stappen geautomatiseerd en vastgelegd. Wat er nu ligt, is een sturingsvraag: welke klant, welke stap en welke medewerker kosten onevenredig veel tijd — en waarom.",
      recognise: [
        "Processen zijn beschreven, maar de KPI per processtap ontbreekt nog",
        "Je weet globaal welke klanten veel tijd kosten, maar niet precies waar dat in zit",
        "Verbeterpunten worden gesignaleerd, maar niet systematisch teruggebracht in het proces",
      ],
      steps: [
        "Koppel aan elke processtap één meetpunt en maak dat maandelijks zichtbaar",
        "Maak de marge per klant én per dienst gedurende het jaar zichtbaar",
        "Richt een vaste verbetercyclus in, met eigenaar, deadline en gemeten effect",
      ],
    },
    {
      min: 0.8,
      max: 1,
      level: "Niveau 4 — In flow",
      headline: "Datagedreven en schaalbaar",
      body:
        "Je proces is ingericht, gemeten en overdraagbaar. Groei kost bij jou niet automatisch extra fte. De aandacht verschuift naar het vasthouden van dit niveau en naar het benutten van de data die het proces oplevert.",
      recognise: [
        "Het proces is niet afhankelijk van individuele medewerkers",
        "Afwijkingen komen bovendrijven via signalering, niet via toeval",
        "De data uit de administratie is bruikbaar voor advieswerk richting de klant",
      ],
      steps: [
        "Borg het niveau met een jaarlijkse herijking van proces en applicatielandschap",
        "Zet de procesdata om in adviesproposities richting je klanten",
        "Gebruik de scan als nulmeting voor kantoren of portefeuilles die je overneemt",
      ],
    },
  ],
};
