import type { Scan } from "../types";

export const mkbScan: Scan = {
  slug: "mkb",
  title: "Hoe goed loopt jouw financiële administratie?",
  subtitle: "Ontdek in zes minuten waar in jouw organisatie tijd en werkkapitaal weglekken.",
  audience: "Voor finance & controllers in het MKB",
  intro: "Vierentwintig vragen over inkoop, facturatie, betalen, afsluiten en rapporteren. Je ziet direct je score per onderdeel en krijgt een verbeterrapport in je mailbox.",
  subject: "organisatie",
  categories: [
    {
      code: "A",
      name: "Inkoop & factuurverwerking",
      icon: "📥",
      weight: 0.2,
      lowScoreText:
        "Inkoopfacturen die via persoonlijke mailboxen binnenkomen, zijn de belangrijkste bron van vertraging in de hele keten: ze worden te laat geboekt, te laat goedgekeurd en te laat betaald. Eén centraal factuuradres met automatische herkenning is bijna altijd de ingreep met de kortste terugverdientijd, omdat hij tegelijk het zoekwerk, de betalingsherinneringen en de correcties wegneemt.",
    },
    {
      code: "B",
      name: "Verkoop, facturatie & debiteuren",
      icon: "📤",
      weight: 0.2,
      lowScoreText:
        "Elke dag dat een factuur later de deur uitgaat, is een dag extra werkkapitaal. Bij een organisatie van jouw omvang betekent vijf dagen sneller factureren al snel een structureel lager debiteurensaldo. Begin bij de bron: waar wacht de facturatie op — op uren, op een projectstatus, of op een goedkeuring die niemand bewaakt?",
    },
    {
      code: "C",
      name: "Applicatielandschap & koppelingen",
      icon: "🔌",
      weight: 0.15,
      lowScoreText:
        "Elke handmatige overstap tussen twee applicaties is een plek waar tijd en kwaliteit weglekken. Begin met een plaat van je applicatielandschap: welke applicatie ondersteunt welke stap, en waar worden dezelfde gegevens twee keer ingevoerd. In de praktijk zitten daar bijna altijd twee of drie koppelingen die zichzelf binnen een jaar terugverdienen.",
    },
    {
      code: "D",
      name: "Betaalproces & autorisatie",
      icon: "💳",
      weight: 0.15,
      lowScoreText:
        "Het betaalproces is de stap met het hoogste risico per handeling. Wie de betaallijst opstelt, wie hem controleert en binnen welke termijn dat gebeurt, hoort net zo hard vastgelegd te zijn als de bedragen zelf. Een beschreven betaalproces met functiescheiding en een vaste accordeertermijn kost een dagdeel om vast te leggen en dekt het grootste enkelvoudige risico in de administratie af.",
    },
    {
      code: "E",
      name: "Maandafsluiting & rapportage",
      icon: "📊",
      weight: 0.2,
      lowScoreText:
        "Maandcijfers die na drie weken komen, zijn geschiedschrijving en geen sturing. De doorlooptijd van de afsluiting is bijna nooit een capaciteitsprobleem, maar een volgordeprobleem: er wordt gewacht op stukken, op goedkeuringen en op posten die nog uitgezocht moeten worden. Een afsluitkalender met een deadline per stap haalt er doorgaans een week af zonder extra inzet.",
    },
    {
      code: "F",
      name: "Organisatie, rollen & continuïteit",
      icon: "👥",
      weight: 0.1,
      lowScoreText:
        "Als het proces in één hoofd zit, is elke vakantie een risico en elke overname een verrassing. Processen beschrijven is geen papieren exercitie: het maakt vervanging mogelijk, maakt functiescheiding aantoonbaar en is de voorwaarde om überhaupt te kunnen meten waar het misloopt.",
    },
  ],
  questions: [
    {
      id: 1,
      category: "A",
      text: "Hoe komen inkoopfacturen bij jullie binnen?",
      options: [
        { points: 0, label: "Op papier en op verschillende mailadressen, deels in persoonlijke mailboxen" },
        { points: 1, label: "Per e-mail, verzameld en doorgestuurd door één medewerker" },
        { points: 2, label: "Via één centraal factuuradres" },
        { points: 3, label: "Centraal adres, automatisch ingelezen in scan- en herkensoftware" },
        { points: 4, label: "Centraal en automatisch herkend, met e-facturatie (UBL/Peppol) bij de grootste leveranciers" },
      ],
    },
    {
      id: 2,
      category: "A",
      text: "Hoe verloopt de goedkeuring van inkoopfacturen?",
      options: [
        { points: 0, label: "Op papier of mondeling; achteraf niet te reconstrueren" },
        { points: 1, label: "Per mail rondgestuurd; de status is nergens zichtbaar" },
        { points: 2, label: "Digitale workflow voor een deel van de facturen" },
        { points: 3, label: "Digitale workflow voor alle facturen, met een vastgelegde autorisatiematrix" },
        { points: 4, label: "Digitale workflow met autorisatiematrix én automatische matching met inkooporder en ontvangst" },
      ],
    },
    {
      id: 3,
      category: "A",
      text: "Wordt er vóór de bestelling een inkooporder vastgelegd?",
      options: [
        { points: 0, label: "Nee; medewerkers bestellen zelf en de factuur is de eerste vastlegging" },
        { points: 1, label: "Alleen bij grote uitgaven of investeringen" },
        { points: 2, label: "Voor de meeste inkopen wordt een order vastgelegd" },
        { points: 3, label: "Verplicht boven een drempelbedrag, met budgetcontrole vooraf" },
        { points: 4, label: "Verplicht inkooporderproces met budgetcontrole vooraf en drie-weg-matching" },
      ],
    },
    {
      id: 4,
      category: "A",
      text: "Welk deel van de inkoopfacturen wordt verwerkt zonder handmatige correctie?",
      options: [
        { points: 0, label: "Minder dan 25%" },
        { points: 1, label: "Tussen 25% en 50%" },
        { points: 2, label: "Tussen 50% en 70%" },
        { points: 3, label: "Tussen 70% en 90%" },
        { points: 4, label: "Meer dan 90%" },
      ],
    },
    {
      id: 5,
      category: "B",
      text: "Hoe komt een verkoopfactuur tot stand?",
      options: [
        { points: 0, label: "Handmatig opgesteld in Word of Excel" },
        { points: 1, label: "Handmatig ingevoerd in de boekhouding op basis van aangeleverde gegevens" },
        { points: 2, label: "Vanuit een verkooporder of contract, met handmatige aanvulling" },
        { points: 3, label: "Automatisch vanuit uren, project of contract, met een goedkeuringsstap" },
        { points: 4, label: "Volledig automatisch vanuit de bron, inclusief elektronische verzending naar de klant" },
      ],
    },
    {
      id: 6,
      category: "B",
      text: "Hoe snel na levering of na afloop van de periode staat de factuur bij de klant?",
      options: [
        { points: 0, label: "Wisselend; regelmatig langer dan drie weken" },
        { points: 1, label: "Binnen drie weken" },
        { points: 2, label: "Binnen twee weken" },
        { points: 3, label: "Binnen vijf werkdagen" },
        { points: 4, label: "Binnen twee werkdagen, volgens een vast factuurritme" },
      ],
    },
    {
      id: 7,
      category: "B",
      text: "Hoe is de debiteurenbewaking geregeld?",
      options: [
        { points: 0, label: "Ad hoc, als er liquiditeit nodig is" },
        { points: 1, label: "Handmatige lijst; herinneringen worden door één persoon verstuurd" },
        { points: 2, label: "Vast moment per maand, handmatig uitgevoerd" },
        { points: 3, label: "Geautomatiseerde herinneringen volgens een vast schema" },
        { points: 4, label: "Geautomatiseerd, met escalatietrappen, een eigenaar per klant en sturing op DSO" },
      ],
    },
    {
      id: 8,
      category: "B",
      text: "Weet je hoeveel dagen het gemiddeld duurt voordat een factuur betaald wordt (DSO)?",
      options: [
        { points: 0, label: "Nee" },
        { points: 1, label: "We kennen alleen het totale debiteurensaldo" },
        { points: 2, label: "Het wordt bij de jaarrekening berekend" },
        { points: 3, label: "Het wordt maandelijks gerapporteerd" },
        { points: 4, label: "Continu zichtbaar, met een doelstelling en analyse per klantgroep" },
      ],
    },
    {
      id: 9,
      category: "C",
      text: "Is vastgelegd welke applicatie welke processtap ondersteunt en hoe die applicaties samenhangen?",
      options: [
        { points: 0, label: "Nee, dat zit in de hoofden van een paar mensen" },
        { points: 1, label: "Er is een lijst met applicaties, zonder samenhang" },
        { points: 2, label: "Er is een globaal schema, maar het is verouderd" },
        { points: 3, label: "Er is een actueel schema van applicaties en koppelingen" },
        { points: 4, label: "Actueel schema inclusief datastromen, eigenaarschap per applicatie en een jaarlijkse review" },
      ],
    },
    {
      id: 10,
      category: "C",
      text: "Hoe vaak worden dezelfde gegevens in meer dan één systeem ingevoerd?",
      options: [
        { points: 0, label: "Structureel; bij vrijwel elke relatie, order en mutatie" },
        { points: 1, label: "Regelmatig, het is een bekende ergernis" },
        { points: 2, label: "Bij een paar systemen die niet gekoppeld zijn" },
        { points: 3, label: "Zelden; de belangrijkste koppelingen liggen er" },
        { points: 4, label: "Nooit; stamgegevens worden op één plek onderhouden en gesynchroniseerd" },
      ],
    },
    {
      id: 11,
      category: "C",
      text: "Hoe verloopt de keten van uren en projecten naar facturatie en boekhouding?",
      options: [
        { points: 0, label: "Uren worden in Excel bijgehouden en handmatig doorgezet" },
        { points: 1, label: "Urenregistratie staat los van de projectadministratie" },
        { points: 2, label: "Uren zijn gekoppeld aan projecten; facturatie gebeurt handmatig" },
        { points: 3, label: "Uren, projecten en facturatie zijn gekoppeld in één keten" },
        { points: 4, label: "Volledig gekoppeld, inclusief onderhanden werk en projectresultaat gedurende de maand" },
      ],
    },
    {
      id: 12,
      category: "C",
      text: "Hoe sluit de salarisadministratie aan op de financiële administratie?",
      options: [
        { points: 0, label: "De loonjournaalpost wordt handmatig ingeboekt" },
        { points: 1, label: "Handmatig, via een importbestand" },
        { points: 2, label: "Grotendeels geautomatiseerd, met handmatige controle achteraf" },
        { points: 3, label: "Automatisch doorgeboekt en periodiek aangesloten" },
        { points: 4, label: "Automatisch doorgeboekt met verbijzondering naar kostenplaats of project, en een vaste aansluitingscontrole" },
      ],
    },
    {
      id: 13,
      category: "D",
      text: "Hoe komt de betaallijst tot stand?",
      options: [
        { points: 0, label: "Er is geen vaste betaallijst; er wordt betaald wanneer een leverancier belt" },
        { points: 1, label: "Per keer een handmatig samengesteld overzicht" },
        { points: 2, label: "Betaaladvieslijst uit de boekhouding, op wisselende momenten" },
        { points: 3, label: "Betaaladvieslijst uit de boekhouding, op een vast moment per week" },
        { points: 4, label: "Vast ritme, automatisch gegenereerd op vervaldatum en betalingskorting" },
      ],
    },
    {
      id: 14,
      category: "D",
      text: "Wie controleert en accordeert de betaallijst, en binnen welke termijn?",
      options: [
        { points: 0, label: "Eén persoon stelt op, accordeert en betaalt; er is geen tweede paar ogen" },
        { points: 1, label: "Er wordt geaccordeerd, maar zonder vaste termijn en zonder vastlegging" },
        { points: 2, label: "Vaste accordeerder, wisselende termijn" },
        { points: 3, label: "Vaste accordeerder en een vastgelegde termijn van enkele werkdagen" },
        { points: 4, label: "Vastgelegd in een autorisatiematrix met vervanging bij afwezigheid; de doorlooptijd wordt gemeten" },
      ],
    },
    {
      id: 15,
      category: "D",
      text: "Hoe wordt de betaalopdracht bij de bank aangeboden?",
      options: [
        { points: 0, label: "Betalingen worden handmatig, één voor één, in de bankomgeving ingevoerd" },
        { points: 1, label: "SEPA-bestand handmatig gedownload en geüpload" },
        { points: 2, label: "SEPA-bestand, met fiattering door twee personen bij de bank" },
        { points: 3, label: "Directe koppeling tussen boekhouding en bank, met fiattering door twee personen" },
        { points: 4, label: "Directe koppeling en twee-personenfiattering, met automatische terugkoppeling van de verwerkte betalingen" },
      ],
    },
    {
      id: 16,
      category: "D",
      text: "Hoe is het risico op onterechte betalingen afgedekt, bijvoorbeeld bij een gewijzigd rekeningnummer?",
      options: [
        { points: 0, label: "Daar is geen procedure voor" },
        { points: 1, label: "We letten erop, maar het is niet vastgelegd" },
        { points: 2, label: "Wijzigingen worden telefonisch geverifieerd; dat wordt niet vastgelegd" },
        { points: 3, label: "Vastgelegde procedure voor het wijzigen van crediteurgegevens, met functiescheiding" },
        { points: 4, label: "Vastgelegde procedure, functiescheiding, naam-nummercontrole en periodieke controle op mutaties in het crediteurenbestand" },
      ],
    },
    {
      id: 17,
      category: "E",
      text: "Wanneer is de maandafsluiting afgerond?",
      options: [
        { points: 0, label: "Er is geen maandafsluiting" },
        { points: 1, label: "Meer dan twintig werkdagen na maandeinde" },
        { points: 2, label: "Binnen vijftien werkdagen" },
        { points: 3, label: "Binnen tien werkdagen" },
        { points: 4, label: "Binnen vijf werkdagen, volgens een vaste afsluitkalender" },
      ],
    },
    {
      id: 18,
      category: "E",
      text: "Werk je met een vaste afsluitchecklist?",
      options: [
        { points: 0, label: "Nee, iedereen doet het op eigen wijze" },
        { points: 1, label: "Er is een lijst, maar die wordt weinig gebruikt" },
        { points: 2, label: "Vaste checklist in Excel of op papier" },
        { points: 3, label: "Checklist in het systeem, met per stap een verantwoordelijke" },
        { points: 4, label: "Checklist met verantwoordelijke, deadline per stap en voortgangsbewaking" },
      ],
    },
    {
      id: 19,
      category: "E",
      text: "Wat is de stand van tussenrekeningen en nog te verklaren posten aan het eind van de maand?",
      options: [
        { points: 0, label: "Daar kijken we pas bij de jaarafsluiting naar" },
        { points: 1, label: "Er staat structureel een saldo dat doorschuift" },
        { points: 2, label: "We ruimen het per kwartaal op" },
        { points: 3, label: "Bij elke maandafsluiting op nul, op enkele uitzonderingen na" },
        { points: 4, label: "Actief gemonitord, met een eigenaar per post en een maximale doorlooptijd" },
      ],
    },
    {
      id: 20,
      category: "E",
      text: "Welke informatie krijgt de directie na afloop van de maand?",
      options: [
        { points: 0, label: "Alleen een saldibalans, of niets" },
        { points: 1, label: "Cijfers uit de boekhouding, zonder toelichting" },
        { points: 2, label: "Een rapportage met toelichting, handmatig opgemaakt in Excel" },
        { points: 3, label: "Een vaste managementrapportage met begrotingsvergelijking" },
        { points: 4, label: "Een dashboard met KPI's, forecast en analyse op afwijkingen, beschikbaar in de eerste week" },
      ],
    },
    {
      id: 21,
      category: "F",
      text: "Zijn de administratieve processen beschreven, met per stap een verantwoordelijke?",
      options: [
        { points: 0, label: "Nee" },
        { points: 1, label: "Deels, en die beschrijving is verouderd" },
        { points: 2, label: "Beschreven voor de belangrijkste processen" },
        { points: 3, label: "Beschreven per processtap, inclusief de verantwoordelijke" },
        { points: 4, label: "Beschreven per processtap, met verantwoordelijke én meetpunt, jaarlijks geactualiseerd" },
      ],
    },
    {
      id: 22,
      category: "F",
      text: "Wat gebeurt er als de sleutelmedewerker van de administratie twee weken uitvalt?",
      options: [
        { points: 0, label: "Dan staat een groot deel van het proces stil" },
        { points: 1, label: "Collega's vangen het op, met vertraging en fouten" },
        { points: 2, label: "Er is een vervanger, maar zonder beschreven proces" },
        { points: 3, label: "Beschreven proces met een aangewezen vervanger per taak" },
        { points: 4, label: "Taken zijn overdraagbaar, vastgelegd en de vervanging is een keer geoefend" },
      ],
    },
    {
      id: 23,
      category: "F",
      text: "Is er functiescheiding tussen vastleggen, accorderen en betalen?",
      options: [
        { points: 0, label: "Nee, één persoon doet het hele traject" },
        { points: 1, label: "Deels; in de praktijk vervaagt het" },
        { points: 2, label: "Op papier geregeld, maar niet in het systeem afgedwongen" },
        { points: 3, label: "Geregeld en in het systeem afgedwongen voor de belangrijkste stappen" },
        { points: 4, label: "Volledig afgedwongen in het systeem, met periodieke controle op de autorisaties" },
      ],
    },
    {
      id: 24,
      category: "F",
      text: "Wat gebeurt er als iemand een verbeterpunt in het proces signaleert?",
      options: [
        { points: 0, label: "Het blijft meestal bij een opmerking" },
        { points: 1, label: "Het wordt besproken; opvolging is toevallig" },
        { points: 2, label: "Het komt op een lijst en af en toe pakken we iets op" },
        { points: 3, label: "Vaste verbetercyclus, met eigenaar en deadline" },
        { points: 4, label: "Vaste cyclus, gemeten effect, en de verbetering wordt in de procesbeschrijving verwerkt" },
      ],
    },
  ],
  profileQuestions: [
    {
      id: "P1",
      text: "In welke sector is jouw organisatie actief?",
      type: "single",
      section: "contact",
      options: [
        "Techniek, engineering & advies",
        "Bouw & installatie",
        "Industrie & productie",
        "Groothandel & logistiek",
        "Zakelijke dienstverlening",
        "Anders",
      ],
    },
    {
      id: "P2",
      text: "Hoeveel medewerkers telt de organisatie?",
      type: "single",
      section: "Algemeen profiel",
      options: [
        "10 – 50",
        "51 – 100",
        "101 – 250",
        "Meer dan 250",
      ],
    },
    {
      id: "P3",
      text: "Welk ERP- of boekhoudpakket gebruiken jullie?",
      type: "single",
      section: "Algemeen profiel",
      options: [
        "Exact",
        "AFAS",
        "NetSuite",
        "Odoo",
        "Twinfield",
        "Visma",
        "Microsoft Dynamics",
        "Anders",
      ],
    },
    {
      id: "P4",
      text: "Hoe groot is de financiële afdeling?",
      type: "single",
      section: "Algemeen profiel",
      options: [
        "1 fte",
        "2 – 3 fte",
        "4 – 6 fte",
        "Meer dan 6 fte",
      ],
    },
    {
      id: "P5",
      text: "Waar zit op dit moment je grootste frustratie in de administratie?",
      type: "text",
      section: "Wat wil je bereiken",
    },
    {
      id: "P6",
      text: "Wat wil je over twaalf maanden bereikt hebben?",
      type: "multi",
      section: "Wat wil je bereiken",
      options: [
        "Snellere maandcijfers",
        "Minder handwerk in de verwerking",
        "Beter zicht op projectresultaat en marge",
        "Kortere betaaltermijn van klanten",
        "Groei aankunnen zonder extra fte op de administratie",
        "Minder afhankelijk van één sleutelpersoon",
      ],
    },
  ],
  tiers: [
    {
      min: 0,
      max: 0.39,
      level: "Niveau 1 — Reactief",
      headline: "De administratie loopt achter de feiten aan",
      body:
        "De organisatie draait, maar de administratie volgt de gebeurtenissen in plaats van ze te sturen. Cijfers komen zo laat dat ze niet meer bruikbaar zijn voor een beslissing, en veel kennis zit in het hoofd van één of twee mensen.",
      recognise: [
        "Facturen worden teruggezocht in mailboxen",
        "Er wordt betaald wanneer een leverancier erachteraan belt",
        "De maandcijfers zijn er zo laat dat de directie ze niet meer gebruikt",
      ],
      steps: [
        "Leg één centraal factuuradres vast voor alle inkoopfacturen",
        "Beschrijf het betaalproces met per stap een verantwoordelijke en een termijn",
        "Zet een afsluitkalender op met een vaste opleverdatum voor de maandcijfers",
      ],
    },
    {
      min: 0.4,
      max: 0.59,
      level: "Niveau 2 — Beheerst handwerk",
      headline: "Het klopt, maar het kost te veel mensen",
      body:
        "De basis staat: er zijn afspraken, er is software en de cijfers kloppen. De winst zit nu niet meer in harder werken, maar in het wegnemen van de handmatige schakels tussen systemen en tussen afdelingen.",
      recognise: [
        "Dezelfde gegevens worden in meerdere systemen ingevoerd",
        "De maandcijfers zijn er pas na twee tot drie weken",
        "Facturatie en debiteurenbewaking hangen aan één persoon",
      ],
      steps: [
        "Richt een digitale factuurworkflow in met een vastgelegde autorisatiematrix",
        "Koppel uren en projecten aan de facturatie, zodat facturen sneller de deur uitgaan",
        "Maak twee cijfers zichtbaar: doorlooptijd van de maandafsluiting en DSO",
      ],
    },
    {
      min: 0.6,
      max: 0.79,
      level: "Niveau 3 — Gestroomlijnd",
      headline: "Het proces staat; de stuurinformatie kan scherper",
      body:
        "De belangrijkste stappen zijn geautomatiseerd en vastgelegd. Wat er nu ligt, is een sturingsvraag: welke processtap, welk project en welke klant kosten onevenredig veel tijd of werkkapitaal — en waarom.",
      recognise: [
        "De maandafsluiting is op tijd, maar de analyse achter de cijfers ontbreekt",
        "Functiescheiding is geregeld op papier, niet afgedwongen in het systeem",
        "Verbeterpunten worden gesignaleerd, maar landen niet in het proces",
      ],
      steps: [
        "Breng de maandafsluiting naar vijf werkdagen met een deadline per stap",
        "Voeg forecast en afwijkingsanalyse toe aan de managementrapportage",
        "Dwing autorisaties af in het systeem en controleer ze periodiek",
      ],
    },
    {
      min: 0.8,
      max: 1,
      level: "Niveau 4 — In control",
      headline: "Snel, aantoonbaar en niet persoonsafhankelijk",
      body:
        "De administratie levert snel, is controleerbaar en draait door als iemand wegvalt. De aandacht verschuift van het produceren van cijfers naar het benutten ervan: werkkapitaal, inkoopvoorwaarden en projectmarge.",
      recognise: [
        "De cijfers liggen er binnen een week, mét analyse",
        "Het proces draait door bij uitval van een sleutelpersoon",
        "Betalings- en autorisatierisico's zijn aantoonbaar afgedekt",
      ],
      steps: [
        "Herijk proces en applicatielandschap jaarlijks, met een vaste eigenaar",
        "Zet de procesdata in op werkkapitaal, inkoopvoorwaarden en projectmarge",
        "Gebruik de scan als nulmeting bij een overname of een nieuwe vestiging",
      ],
    },
  ],
};
